Survey/Models/Survey.cs
using Survey.Serializer;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Survey.Models
{
    public enum LanguageEnum
    {
        [Description("Български")]
        Bulgarian,
        [Description("English")]
        English,
        [Description("Русский")]
        Russian,
        [Description("Español")]
        Spanish,
        [Description("Türkçe")]
        Turkish,
        [Description("Украинский")]
        Ukrainian
    }
    public class Survey
    {
        public int Id { get; set; }
        public bool IsActive { get; set; }

        public LanguageEnum TranslationLanguage { get; set; }

        [System.Xml.Serialization.XmlIgnore]
        public Dictionary<LanguageEnum, Survey> Languages { get; set; }

        [Required]
        public string Title { get; set; }        
        public string Description { get; set; }
        public string ThankYouMessage { get; set; }
        public List<Question> Questions { get; set; }


        [System.Xml.Serialization.XmlIgnore]
        public List<SurveyAnswer> Answers { get; set; }

        public Question FindQuestionById(int id)
        {
            foreach (Question q in Questions)
            {
                if (q.Id == id)
                {
                    return q;
                }
            }

            return null;
        }


        public void Update(Question newQuestion)
        {
            int questionInd = QustionIndex(newQuestion);
            Questions[questionInd] = newQuestion;
        }

        public void Update(Survey source)
        {
            Title = source.Title;
            Description = source.Description;
            ThankYouMessage = source.ThankYouMessage;
            IsActive = source.IsActive;
        }

        [System.Xml.Serialization.XmlIgnore]
        public Dictionary<LanguageEnum, string> Translations
        {
            get
            {
                XmlSurveySerializer serializer = new XmlSurveySerializer();
                List<LanguageEnum> translations = serializer.Translations(Id);
                return LanguageStrings(translations);
            }
        }

        [System.Xml.Serialization.XmlIgnore]
        public List<LanguageEnum> NotInTranslations
        {
            get
            {
                XmlSurveySerializer serializer = new XmlSurveySerializer();
                return serializer.NotInTranslations(Id);
            }
        }

        private int QustionIndex(Question question)
        {
            int questionInd = 0;
            foreach (Question q in Questions)
            {
                if (question.Id == q.Id)
                {
                    break;
                }
                questionInd++;
            }

            return questionInd;
        }

        public Dictionary<LanguageEnum, string> LanguageStrings(List<LanguageEnum> languages)
        {
            Dictionary<LanguageEnum, string> dict = new Dictionary<LanguageEnum, string>();
            foreach(LanguageEnum lang in languages)
            {
                if (lang == LanguageEnum.Bulgarian)
                {
                    dict.Add(lang, "Български");
                }
                else if (lang == LanguageEnum.English)
                {
                    dict.Add(lang, "English");
                }
                else if (lang == LanguageEnum.Russian)
                {
                    dict.Add(lang, "Русский");
                }
                else if (lang == LanguageEnum.Spanish)
                {
                    dict.Add(lang, "Español");
                }
                else if (lang == LanguageEnum.Turkish)
                {
                    dict.Add(lang, "Türkçe");
                }
                else if (lang == LanguageEnum.Ukrainian)
                {
                    dict.Add(lang, "Украинский");
                }
                
            }
            return dict;
        }
    }
}

Survey/Controllers/QuestionController.cs
using Survey.Models;
using Survey.Serializer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Survey.Controllers
{
    [Authorize]
    public class QuestionController : AppController
    {
        // GET: Question
        [HttpGet]
        public ActionResult Edit(int questionId, int surveyId, LanguageEnum ? language)
        {
            if (!language.HasValue)
            {
                language = LanguageEnum.English;
            }
            SurveySerializer serializer = new XmlSurveySerializer();
            Survey.Models.Survey survey = serializer.Load(surveyId, language.Value);
            if (survey == null)
            {
                return RedirectToError("Survey does not exist.");
            }

            Question question = null;
            if (questionId == 0)
            {
                question = new Question(survey, QuestionType.Text);
                survey.Questions.Add(question);

                try
                {
                    serializer.Write(survey);
                }
                catch (Exception e)
                {
                    return RedirectToError(e);
                }
            }
            else
            {
                question = survey.FindQuestionById(questionId);
                if (question == null)
                {
                    return RedirectToError("Question does not exist.");
                }
            }

            return View(question);
        }

        [HttpPost]
        public ActionResult Edit(Question question)
        {
            

            if (question.Type != QuestionType.Text && question.Options.Count == 0)
            {
                ModelState.AddModelError("Options", "You have not added any options.");
                return View(question);
            }


            if (question.Options != null)
            {
                int optionId = 1;
                foreach (QuestionOption option in question.Options)
                {
                    option.Id = optionId;
                    option.Language = question.QuestionLanguage;
                    option.Number = optionId;
                    option.QuestionId = question.Id;
                    optionId++;
                }

                QuestionOption lastOption = question.Options[question.Options.Count - 1];
                lastOption.IsOther = QuestionOption.DetermineIsOther(lastOption);                
            }

            SurveySerializer serializer = new XmlSurveySerializer();
            Survey.Models.Survey survey = serializer.Load(question.SurveyId, question.QuestionLanguage);
            if (survey == null)
            {
                return RedirectToError("Survey does not exist.");
            }
            survey.Update(question);

            try
            {
                serializer.Write(survey);
            }
            catch (Exception e)
            {
                return RedirectToError(e);
            }
            
            
            return RedirectToAction("Edit", "Survey", new {id = survey.Id, language = question.QuestionLanguage});
        }
    }
}

Survey/Controllers/SurveyController.cs
using Survey.Models;
using Survey.Serializer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using OfficeOpenXml;

namespace Survey.Controllers
{
    [Authorize]
    public class SurveyController : AppController
    {
        // GET: Survey
        public ActionResult Index(LanguageEnum ? language)
        {
            if (!language.HasValue)
            {
                language = LanguageEnum.English;
            }
            SurveySerializer surveySerializer = new XmlSurveySerializer();
            List<Survey.Models.Survey> surveys = surveySerializer.Load(language.Value);
            return View(surveys);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Survey.Models.Survey survey)
        {
            if (!ModelState.IsValid)
            {
                return View(survey);
            }

            SurveySerializer serializer = new XmlSurveySerializer();
            try
            {
                serializer.Write(survey);
            }
            catch (Exception e)
            {
                return RedirectToError(e);
            }


            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id, LanguageEnum ? language)
        {
            if (!language.HasValue)
            {
                language = LanguageEnum.English;
            }

            SurveySerializer serializer = new XmlSurveySerializer();
            Survey.Models.Survey survey = serializer.Load(id, language.Value);
            if (survey == null)
            {
                return RedirectToError("Survey does not exists.");
            }

            return View(survey);
        }

        [HttpPost]
        public ActionResult Edit(Survey.Models.Survey survey)
        {
            SurveySerializer serializer = new XmlSurveySerializer();
            Survey.Models.Survey existingSurvey = serializer.Load(survey.Id, survey.TranslationLanguage);
            if (existingSurvey == null)
            {
                return RedirectToError("The survey does not exists.");
            }

            existingSurvey.Update(survey);
            serializer.Write(existingSurvey);
            return View(existingSurvey);
        }

        [HttpGet]
        public ActionResult AddNewTranslation(int surveyId)
        {
            SurveySerializer serializer = new XmlSurveySerializer();
            Survey.Models.Survey survey = serializer.Load(surveyId, LanguageEnum.English);
            if (survey == null)
            {
                return RedirectToError("Survey does not exists.");
            }

            List<LanguageEnum> noTranslations = survey.NotInTranslations;

            ViewBag.SurveyId = surveyId;
            return View(noTranslations);
        }

        [HttpPost]
        public ActionResult AddNewTranslation(int surveyId, LanguageEnum language)
        {
            XmlSurveySerializer serializer = new XmlSurveySerializer();
            Survey.Models.Survey translation = serializer.Load(surveyId, LanguageEnum.English);
            if (translation == null)
            {
                return RedirectToError("Survey does not exists.");
            }

            translation.TranslationLanguage = language;
            foreach (Question q in translation.Questions)
            {
                q.QuestionLanguage = language;

                foreach (QuestionOption o in q.Options)
                {
                    o.Language = language;
                }
            }

            try
            {
                serializer.Write(translation);
            }
            catch(Exception e)
            {
                return RedirectToError(e);
            }

            return RedirectToAction("Index");
        }

        public ActionResult DownloadExcel(int surveyId)
        {
            string fileName = ExcelSerializer.GetSurveyDescriptionFile(surveyId);
            if (!System.IO.File.Exists(fileName))
            {
                return RedirectToError("No excel file.");
            }

            FileInfo file = new FileInfo(fileName);
            using (ExcelPackage package = new ExcelPackage(file))
            {
                MemoryStream memStream = new MemoryStream();
                package.SaveAs(memStream);
                string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                string downloadFileName = "Survey_" + surveyId + ".xlsx";
                memStream.Position = 0;

                FileStreamResult fileStreamResult = new FileStreamResult(memStream, contentType);
                fileStreamResult.FileDownloadName = downloadFileName;
                return fileStreamResult;
            }            
        }
    }
}

Survey/Views/Survey/AddNewTranslation.cshtml
@model System.Collections.Generic.List<Survey.Models.LanguageEnum>

@{
    ViewBag.Title = "AddNewTranslation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add New Translation</h2>
@using (Html.BeginForm(new { surveyId = ViewBag.SurveyId }))
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.Label("Language", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("language", new SelectList(Model))
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to the list of surveys", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Survey/Views/Survey/Create.cshtml
@model Survey.Models.Survey
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Survey</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.TranslationLanguage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.TranslationLanguage)
                @Html.ValidationMessageFor(model => model.TranslationLanguage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, 10, 60, null)
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThankYouMessage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ThankYouMessage, 10, 60, null)
                @Html.ValidationMessageFor(model => model.ThankYouMessage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to the list of surveys", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Survey/Views/Survey/Edit.cshtml
@model Survey.Models.Survey
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SurveyLanguage</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.TranslationLanguage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.TranslationLanguage)
                @Html.ValidationMessageFor(model => model.TranslationLanguage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, 10, 60, null)
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThankYouMessage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ThankYouMessage, 10, 60, null)
                @Html.ValidationMessageFor(model => model.ThankYouMessage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <h4>Questions</h4>
    <p>
        @Html.ActionLink("Add new question", "Edit", "Question", new { questionId = 0, surveyId = @Model.Id}, null) 
    </p>
    <hr />
    @foreach (Survey.Models.Question question in @Model.Questions)
    {
        @Html.DisplayFor(modelItem => question)
    }
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Survey/Views/Survey/Index.cshtml
@model IEnumerable<Survey.Models.Survey>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>Translations</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @foreach(KeyValuePair<Survey.Models.LanguageEnum, string> lang in item.Translations)
            {
                @Html.ActionLink(lang.Value, "Edit", new { id = item.Id, language = lang.Key }) @:|
            }
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Add translations", "AddNewTranslation", new {surveyId = item.Id}) |
            @Html.ActionLink("Answer", "Index", "SurveyAnswer", new { id = item.Id, language = Survey.Models.LanguageEnum.English}, null) |
            @Html.ActionLink("Download excel", "DownloadExcel", new { surveyId = item.Id })
        </td>
    </tr>
}

</table>